# Generated by Django 5.2.8 on 2025-11-09 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_options_alter_project_vote_ratio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_total', '-vote_ratio', '-created']},
        ),
    ]
